### ISSUE TITLE
set_flash not detecting values despite them being there

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/shoulda-matchers#857] opened 2015-12-09 21:59 UTC
Using a `set_flash` matcher in this test

```
describe "a POST to #create with username and incorrect password" do

  before do 
    post :create, session: { username: @user.username, password: 'foobar' }
  end

  it { should_not redirect_to_url_after_create }
  it { should render_template(:new) }
  it { should set_flash.to t('flashes.failure_after_create') }
  it { should_not be_signed_in }
end
```

I get an error saying:

```
Expected Admin::Clearance::SessionsController to set any key in flash to "Bad username or password", but it did not
```

But when I check the flash in a puts statement right before the failed `set_flash` call, it logs

```
......{"notice"=>"Bad username or password"}
F
```

So why isn't `set_flash` detecting this flash correctly in `flash["notice"]`?

**Comment by mcmire** [comment] 2015-12-09 22:40
I'm actually not sure. There's a [test](https://github.com/thoughtbot/shoulda-matchers/blob/master/spec/support/unit/shared_examples/set_session_or_flash.rb#L114) for this, so I'm not sure what to tell you. Is there a way you can reproduce this in a fresh Rails app?

**Comment by coneybeare** [comment] 2015-12-10 00:51
I'll try. Though it isn't fresh, I am using Clearance, and other thoughtbot gems.

**Comment by coneybeare** [comment] 2015-12-10 00:55
Another example:

````
it 'sets the fucking flash' do
  post :create, session: { username: @user.username, password: 'fuck this' }
  expect(flash[:notice]).to eq(t('flashes.failure_after_create'))
  should set_flash.to t('flashes.failure_after_create') # FAILS HERE, BUT NOT ABOVE
end
````

**Comment by mcmire** [comment] 2015-12-14 17:29
Ok. Let's tone it down a bit, huh?

**Comment by coneybeare** [comment] 2015-12-14 17:34
haha, that wasn't directed at you, I tend to write tests like a f***ing boss. Usually I censor out when posting publicly but forgot to do so here. Sorry for the vulgarity

**Comment by mcmire** [comment] 2015-12-14 17:38
Haha, alright :)

**Comment by DexterTheDragon** [comment] 2016-02-17 17:51
This appears to be a problem with Rails 4.0. The problem code is [this line](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/action_controller/flash_store.rb#L29). Starting in Rails 4.1 the flash keys are normalized to a string. In Rails < 4.1 if you set a flash as `flash[:notice] = "message"` then the key is kept as a symbol and since the matcher only checks for string keys it fails.

**Comment by agbodike** [comment] 2016-02-25 09:35
Looks like you now know the problem, but I have the same issue in rails 4.0.13.

Of the following two tests:

```
it { (flash[:error]).should be_present }
it { should set_flash[:error] }
```
The first works fine, but the second fails with the following error:

```
Failure/Error: it { should set_flash[:error] }
  Expected SurveysController to set flash[:error], but it did not
```

**Comment by mcmire** [comment] 2020-05-06 07:35
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!

**Closed by mcmire** 2020-05-06 07:35 UTC
Labels: 🕷 Issue: Bug, 🤔 Issue: Need to Investigate
