### ISSUE TITLE
uniqueness failing but not expected behavior.

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/shoulda-matchers#1017] opened 2017-05-06 23:41 UTC
rails 5.0.02
project via tbot suspenders
using Faker for test data.
using rails 5 branch of shoulda-matchers `rails-5`

``` 
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end
```

```   
it { should validate_uniqueness_of(:email) } => 
     Failure/Error: it { should validate_uniqueness_of(:email) }

       User did not properly validate that :email is case-sensitively unique.
         After taking the given User, whose :email is
         ‹"dennis@gleichner.info"›, and saving it as the existing record, then
         making a new User and setting its :email to a different value,
         ‹"DENNIS@GLEICHNER.INFO"›, the matcher expected the new User to be
         valid, but it was invalid instead, producing these validation errors:

         * email: ["has already been taken"]
```
This spec passes. As this is the expected behavior. 
```
    it "email uniqueness is case-sensitive" do
      user = build(:user)
      user_2 = build(:user, email: user.email.upcase)

      user.save
      user_2.save

      expect(user_2.valid?).to eq false
      expect(user_2.errors).to include :email
    end
```

case sensitive is defaulted to true, why is the uniqueness validator raising that error?

**Comment by mcmire** [comment] 2017-05-11 14:54
@ChrisCPO Hmm. That's a good question!

Can you reproduce this in a fresh Rails 5 app and post a link to the repo if necessary?

**Comment by mcmire** [comment] 2017-07-25 17:02
Hey @ChrisCPO. Do you have any more information that could help us debug this issue?

**Comment by ChrisCPO** [comment] 2017-08-17 20:05
@mcmire, sorry notification slipped through let me check.

**Comment by ChrisCPO** [comment] 2017-09-02 19:25
@mcmire  here ya go, commit has notes.
https://github.com/ChrisCPO/matcher-issue/commit/995a6a86ef51f4fe845d270a95c78a6cda5717ee

**Comment by mcmire** [comment] 2017-09-08 06:05
@ChrisCPO Thanks for that! That was really helpful.

This is indeed caused by Clearance. Clearance will actually downcase `email` when validations are run. Therefore, this interferes slightly with the uniqueness matcher. To get around this, you need to say:

``` ruby
it { should validate_uniqueness_of(:email).ignoring_case_sensitivity }
```

**Comment by mcmire** [comment] 2017-10-05 07:13
I'm going to close this for now, but let me know if you are still seeing issues with this.

**Closed by mcmire** 2017-10-05 07:13 UTC
Labels: Issue: Need to Investigate, Rails 5
