### ISSUE TITLE
Rails 5.0.0.1,  error with 'validate_inclusion_of'

### ISSUE THREAD

**Issue by dissident** [thoughtbot/shoulda-matchers#958] opened 2016-08-29 06:44 UTC
Hello, after upgrade my Rails to 5.0.0.1 and shoulda-matchers to last version, I got an error in my spec.

[my spec](https://github.com/metastudio/cashbox/blob/master/spec/models/bank_account_spec.rb)
`30.    it { expect(subject).to validate_inclusion_of(:currency).in_array(%w(USD RUB)) }`

[my model](https://github.com/metastudio/cashbox/blob/master/app/models/bank_account.rb)

error:
![image](https://cloud.githubusercontent.com/assets/3728600/18043009/2e7329f4-6def-11e6-9db3-e1c9c31bc342.png)

I tried to go back to the previous version of shoulda-matchers (2.8.0), but it has not brought results.
I do not understand why it happened.

**Comment by mcmire** [comment] 2016-08-29 22:21
@dissident I would check the backtrace. I don't think this is anything shoulda-matchers is doing -- it looks like something in your model is trying to access or set a `residue_cents` attribute as a part of validation, and this attribute does not exist.

**Comment by dissident** [comment] 2016-08-30 14:07
backtrace
```
  1) BankAccount validation should validate that :currency is either ‹"USD"› or ‹"RUB"›
     Failure/Error: it { expect(subject).to validate_inclusion_of(:currency).in_array(%w(USD RUB)) }
     
     ActiveModel::MissingAttributeError:
       can't write unknown attribute `residue_cents`
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activerecord-5.0.0.1/lib/active_record/attribute.rb:182:in `with_value_from_database'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activerecord-5.0.0.1/lib/active_record/attribute_set.rb:51:in `write_from_user'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/write.rb:50:in `write_attribute_with_type_cast'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/write.rb:32:in `write_attribute'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/money-rails-1.6.2/lib/money-rails/active_record/monetizable.rb:136:in `block (2 levels) in monetize'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:149:in `block in validate'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:148:in `each'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:148:in `validate'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:405:in `public_send'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:405:in `block in make_lambda'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `catch'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:546:in `block in default_terminator'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validations.rb:408:in `run_validations!'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activemodel-5.0.0.1/lib/active_model/validations.rb:338:in `valid?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:65:in `valid?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:96:in `perform_validation'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:89:in `validation_result'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:85:in `validation_error_messages'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:64:in `messages'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:25:in `has_messages?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:55:in `messages_match?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validator.rb:21:in `call'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:38:in `matches?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:42:in `does_not_match?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `each'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `detect'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setters_and_validators.rb:28:in `first_failing'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `public_send'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:533:in `run'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/allow_value_matcher.rb:394:in `matches?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:155:in `run_allow_or_disallow_matcher'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validation_matcher.rb:88:in `allows_value_of'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:431:in `block in allows_all_values_in_array?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:430:in `each'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:430:in `all?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:430:in `allows_all_values_in_array?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:402:in `matches_for_array?'
     # /home/stas/.rvm/gems/ruby-2.3.1@cashbox/gems/shoulda-matchers-3.1.1/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:383:in `matches?'
     # ./spec/models/bank_account_spec.rb:31:in `block (3 levels) in <top (required)>'
```

**Comment by dissident** [comment] 2016-08-30 14:12
This occurs only with this matcher, two matchers before work correctly.

**Comment by mcmire** [comment] 2016-08-30 19:48
Okay, try writing the following in a test. Does this raise an error as well?

```
account = BankAccount.new
account.currency = "something else"
account.valid?
```

**Comment by dissident** [comment] 2016-08-31 05:06
No, the code works, returns false.

**Comment by mcmire** [comment] 2016-08-31 16:21
@dissident Okay. Do you think you could create a fresh Rails app and try to reproduce it there? I am thinking this has to do with the fact that you're using the `money-rails` gem, and it may require that certain attributes be set.

**Comment by dissident** [comment] 2016-09-01 05:11
@mcmire Okay.I am creating a fresh app and check the behavior of matcher with money-rails gem and without them. After that write here about my observations. Thanks for direction.

**Comment by mcmire** [comment] 2017-07-25 16:46
I'm going to close this since you haven't responded in a while, but feel free to let me know if this is still a problem and I can reopen this.

**Closed by mcmire** 2017-07-25 16:46 UTC
Labels: Need to Investigate
