### ISSUE TITLE
shoulda-matchers looking for join table names including schema

### ISSUE THREAD

**Issue by EllieRagone** [thoughtbot/shoulda-matchers#625] opened 2014-12-09 01:20 UTC
So I've got two models with habtm between them; called Region and User.  So I need a join table called "regions_users"; however, doing:

```
RSpec.describe Region, :type => :model do
  it { should have_and_belong_to_many(:region_admins) }
end
```

Gives me the error:

```
       Expected Region to have a has_and_belongs_to_many association called users (join table public.regions_public.users doesn't exist)
```

Obviously that's not accurate postgres syntax, and the code works as it should.  Please correct me if I'm wrong, but it seems to be a problem with shoulda-matcher.

**Comment by yogodoshi** [comment] 2015-11-03 17:44
I'm  getting a strange error, it may be related. If you don't think so I can open another issue:

```Ruby
class Course < ActiveRecord::Base
  has_and_belongs_to_many :categories, join_table: :course_categories
end

class Category < ActiveRecord::Base
  has_and_belongs_to_many :courses, join_table: :course_categories
end

RSpec.describe Course, type: :model do
  describe 'associations' do
    it { is_expected.to have_and_belong_to_many(:categories).join_table(:course_categories) }
  end
end
```

Error:
```Ruby
Failure/Error: it { is_expected.to have_and_belong_to_many(:categories).join_table(:course_categories) }
       Expected Course to have a has_and_belongs_to_many association called categories (join table course_categories doesn't exist)
```

Using version 3.0.1

**Comment by mcmire** [comment] 2015-11-03 18:48
Obvious question, but just to be sure -- I'm assuming that `course_categories` *does* exist?

**Comment by yogodoshi** [comment] 2015-11-03 19:39
@mcmire yup! its in the schema and I've tried dropping the db, creating again, checked for typos and all that :)

**Comment by mcmire** [comment] 2015-11-03 22:54
@yogodoshi Okay, weird. This *may* be related, but go ahead and make a new issue for this.

If you can re-create this bug in a fresh Rails app and then post it up in a repo, that'll help me zero in on what the deal is here.

**Comment by kofiasare** [comment] 2018-08-21 17:35
@pcragone  please were you able to resolve this issue in your app, I have run into the same problem,
I' having a similar setup where am using apartment gem
```ruby

class User < ApplicationRecord
  has_and_belongs_to_many :markets
end

class Market < ApplicationRecord
  has_and_belongs_to_many :administrators, class_name: 'User'
end

describe User, type: :model do
   it { is_expected.to have_and_belong_to_many :markets }
end
```
Error

```
User should have and belong to many markets
     Failure/Error: it { is_expected.to have_and_belong_to_many :markets }
       Expected User to have a has_and_belongs_to_many association called markets (join table public.markets_users doesn't exist)

**Comment by superchell** [comment] 2019-11-01 12:35
I have the same problem. Did you get a fix?

**Comment by allisonphillips** [comment] 2020-02-20 23:30
I am also experiencing this when trying to add shoulda matcher specs for `has_and_belongs_to_many` relationships for classes that are not dependent on any gem. At first I thought I had forgotten to configure something, but then I reproduced by writing the same example for similar classes that has long been functioning in a production environment without issue. All this syntax works:

```ruby
# class
has_and_belongs_to_many :association_name,
  class_name:              '::AssociationClass',
  join_table:              :join_table_name_that_definitely_exists,
  foreign_key:             foreign_key_id,
  association_foreign_key: association_foreign_key_id

# spec
it do
  should have_and_belong_to_many(:association_name)
    .class_name('::AssociationClass')
    .with_foreign_key(:foreign_key_id)
    .with_foreign_key(:association_foreign_key_id)
end
```

But as soon as I add `.join_table(:join_table_name_that_definitely_exists)` to the example block in the spec, I get the equivalent of this message: 
```ruby
"Expected #{described_class} to have a has_and_belongs_to_many association " \
"called #{association_name} (join table #{join_table_name} doesn't exist)"
```

 Was another issue ever opened for this?

**Comment by nimeshnikum** [comment] 2020-04-26 09:33
@allisonphillips Yes, this was already answered here: https://github.com/thoughtbot/shoulda-matchers/issues/914#issuecomment-195552836

Try dropping the **"s"**. It looks like you have **have_and_belongs_to_many**, the method you want is **have_and_belong_to_many**

**Comment by allisonphillips** [comment] 2020-04-27 20:27
> @allisonphillips Yes, this was already answered here: [#914 (comment)](https://github.com/thoughtbot/shoulda-matchers/issues/914#issuecomment-195552836)
> 
> Try dropping the **"s"**. It looks like you have **have_and_belongs_to_many**, the method you want is **have_and_belong_to_many**
> 
> Million thanks to @adammcfadden for solution!

@nimeshnikum I'm confused... is that supposed to be in response to me? I did not pluralize 'belongs' in my matcher example code, nor did the other commenters. The references to `has_and_belongs_to_many` in this thread are sample code for the association definitions in the class (which is the correctly named Rails method [#has_and_belongs_to_many](https://api.rubyonrails.org/v5.2.4/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many)), not the spec (that's why they start with 'has' instead of 'have'). The issue I and the other users experienced here is that the matcher rejects symbolized join table names. The issue you're linking to has the matcher name misspelled and doesn't use the join table matcher at all.

**Comment by mcmire** [comment] 2020-04-27 20:33
Hi @allisonphillips, I don't think there is an issue around the problem you're seeing (using a symbol with `join_table` not working). Would you mind creating a new issue so that we can track it better?

**Comment by mcmire** [comment] 2020-07-12 17:14
I'm going to close this issue since this is pretty rare and (although I can't say for certain) I don't think it's the fault of shoulda-matchers. The `have_and_belongs_to_many` matcher simply asks the Reflection object for the association what table name it thinks is associated. If you think the matcher has got it wrong you can override the join table name using `have_and_belongs_to_many(...).join_table(...)`. If someone else out there is using Apartment and runs into this again, then I'm happy to look further into it but for now I'm going to close this so as not to clutter up the issues list.

**Closed by mcmire** 2020-07-12 17:14 UTC
Labels: 🕷 Issue: Bug

**Comment by allisonphillips** [comment] 2020-07-23 22:29
> Hi @allisonphillips, I don't think an Issue has been created yet around the problem you're seeing (using a symbol with `join_table` not working). Would you mind creating a new one so that we can track it better?

Done, see https://github.com/thoughtbot/shoulda-matchers/issues/1321. Thank you!
