### ISSUE TITLE
named routes are not available when using with Minitest

### ISSUE THREAD

**Issue by badaiaqrandista** [thoughtbot/shoulda-matchers#788] opened 2015-10-04 11:03 UTC
Hi,

Thanks for the gem. I hope you guys can help me with this issue.

I'm using Rails 4.2.4. I can't use named routes when using shoulda matchers in my test. But if I convert the test to the normal Minitest syntax, the named route is available. 

Route:

``` ruby
Rails.application.routes.draw do
  root 'welcome#index'
  scope '/admin' do
    get '', to: 'welcome#admin_root', as: 'admin_root'
  end
end
```

Controller:

``` ruby
class WelcomeController < ApplicationController
  before_action :authenticate_account!, on: :admin_root

  def index
    redirect_to admin_root_path
  end

  def admin_root
    render 'index'
  end
end
```

Test:

``` ruby
require 'test_helper'

class WelcomeControllerTest < ActionController::TestCase
  should route(:get, '').to(action: :index)

  context "GET welcome#index" do
    setup { get :index }
    should redirect_to(new_account_session_path)
  end
end
```

When I executed the test:

```
$ bin/rake test test/controllers/welcome_controller_test.rb 
rake aborted!
NoMethodError: undefined method `new_account_session_path' for WelcomeControllerTest:Class
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:482:in `method_missing'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:8:in `block in <class:WelcomeControllerTest>'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `instance_exec'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `merge_block'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:313:in `initialize'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `new'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `context'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:6:in `<class:WelcomeControllerTest>'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:3:in `<top (required)>'
```

Gemfile.lock:

```
    shoulda (3.5.0)
      shoulda-context (~> 1.0, >= 1.0.1)
      shoulda-matchers (>= 1.4.1, < 3.0)
```

**Comment by mcmire** [comment] 2015-10-04 20:25
You don't have a route with a name of `new_account_session`, shouldn't you add that first?

**Comment by badaiaqrandista** [comment] 2015-10-04 22:05
Ah sorry, that route is created by devise. But the same error came up with ```admin_root``` route:
```
NoMethodError: undefined method `admin_root_path' for WelcomeControllerTest:Class
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:482:in `method_missing'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:8:in `block in <class:WelcomeControllerTest>'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `instance_exec'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `merge_block'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:313:in `initialize'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `new'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `context'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:6:in `<class:WelcomeControllerTest>'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:3:in `<top (required)>'
```

**Comment by mcmire** [comment] 2015-10-04 22:41
Oh... gotcha.

FYI, this is related to `shoulda-context` and not `shoulda-matchers`. But the problem is that route helpers are available on the instance level, and when you're using `should some_matcher` you're on the class level.

`redirect_to` [happens to take a block form](http://matchers.shoulda.io/docs/v3.0.0/Shoulda/Matchers/ActionController.html#redirect_to-instance_method) for cases like this. Try this:

```
should redirect_to { new_account_session_path }
```

**Comment by badaiaqrandista** [comment] 2015-10-05 06:54
Ah thank you...

I tried ```should redirect_to { new_account_session_path }``` but I got this error:
```
ArgumentError: wrong number of arguments (0 for 1)
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/action_controller/redirect_to_matcher.rb:38:in `redirect_to'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:482:in `method_missing'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:8:in `block in <class:WelcomeControllerTest>'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `instance_exec'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:322:in `merge_block'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:313:in `initialize'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `new'
/Users/xxx/.rvm/gems/ruby-2.2.3@preorder/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:200:in `context'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:6:in `<class:WelcomeControllerTest>'
/Users/xxx/Documents/workspace/preorder/test/controllers/welcome_controller_test.rb:3:in `<top (required)>'
```

I had to change it to ```should redirect_to(nil) { new_account_session_path }``` to make the test succeed.

**Comment by mcmire** [comment] 2015-10-05 16:53
Hmm... I took another look at `redirect_to` and it looks like that argument is meant to be the human-readable representation of the route so that when your test is printed out as they are being run it looks correct. So I think you'd want to say:

```
should redirect_to("GET /account/session") { new_account_session_path }
```

or whatever the URL for that route would be.

This is a documentation bug so I'll leave this issue open.

**Comment by mcmire** [comment] 2020-05-06 07:34
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this issue.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this issue, then please let us know so that we can reprioritize it. Thanks!

**Closed by mcmire** 2020-05-06 07:34 UTC
Labels: 📘 Documentation
