### ISSUE TITLE
4.1.0 breaks not_nil validaton example

### ISSUE THREAD

**Issue by PeterMozesMerl** [thoughtbot/shoulda-matchers#1232] opened 2019-07-08 22:46 UTC
I have one of the few cases when not_nil works while not_blank doesn’t and it shouldn’t.

When I upgraded my gems, I thought it was some upstream that broke it but if I force shoulda-matchers 4.0.1 to stay and upgrade everything else, it doesn’t break.

I have a few tables in PostgreSQL that are integer[], not null,  default '{}'::integer[].

This field type accepts only an array of integer values. The only other value it could accept is the NULL, shouldn’t I’ve declared it as not NULL. In PostgreSQL, there is nothing common between an empty array and NULL. The former means empty and the latter means undefined. 'select [] = NULL' returns neither true nor false but NULL (as it should in a typed system).

For the business logic, it’s normal to have empty arrays in these fields. Having NULL would not be okay because the queries wouldn’t work. At least not the ORM queries, and I would need to write twice as long manual queries handling the NULL value (which doesn’t make sense there in the first place).

For many years, I used 

```
validates :super_hero_ids, not_nil: true
```

This allows Rails to send PostgreSQL an empty array, which is not NULL in PostgreSQL. It would also be okay to send nil that translates to NULL except for the field is defined not NULL.

It wouldn’t be okay to send '' as a value since the answer is 'ERROR:  malformed array literal: ""' from PostgreSQL.

This might be the reason Rails won’t send it an empty string. I didn’t even remember that because I never send my arrays an empty string. But maybe other people do it since Rails seems to translate it to the default value which is [] in this case. I’m not sure it’s better than raising an Exception but I’m sure the global warming is much worse. Or it will be. Soon.

I’ve been using

```
expect(subject).to validate_presence_of :super_hero_ids 
# or
it { is_expected.to validate_presence_of attribute }
```

on these fields.

Starting from 4.1.0, this will say:

```
After setting super_hero_ids to ‹""› -- which was read back as ‹[]› --
  the matcher expected the SuperModel to be invalid, but it was valid
  instead.
```

If I want, I can see the change as an improvement since validates_presence_of :x means the value of x should not be blank. '' is blank.

I’m open to change my examples. The validation should stay as it is because it does what it says, and that’s what it should do. (The only value I don’t want to pass is nil). Presence validation won’t work since [] is blank while the empty array should be accepted. It’s not the validation what’s broken but the examples.

I would rewrite them if I knew a solution.

I’m not aware of any validates_not_null method. The validates_presence_of doesn’t seem to accept additional parameters. 

I could write
```
		expect(subject).to allow_value([]).for :super_hero_ids
		expect(subject).to allow_value([3, 7]).for :super_hero_ids
		expect(subject).to_not allow_value(nil).for :super_hero_ids
```

It works. It’s not expressive. I would need to add a comment. I would need to use four lines instead of one. More like five because if there is a comment for a group of lines, I also add a newline afterward.

I would rather ask you to please either revert the change in the validation, or, probably it would be better to add a not_nil validation example considering that Rails has a 

```
validates xxx, not_nil: true
```

 for a good reason. 

Thanks.

**Comment by mcmire** [comment] 2019-07-09 01:04
Hey, thanks for the bug report. There are some similar issues with the presence matcher other people have reported, and I know why this is happening. I think the matcher simply needs to consider whether the field is an array column and choose not to attempt to set the attribute to `""` if that is the case.

By the way, I've never heard of a `not_nil` option on `validates`. Is this a custom validator that you've created or that you're getting through a gem?

**Comment by mcmire** [comment] 2019-07-09 03:44
I just merged in #1231, which should fix this issue. Can you briefly switch `shoulda-matchers` to use the master branch in your Gemfile and see if that makes this test pass?

**Comment by PeterMozesMerl** [comment] 2019-07-09 09:37
I’m surprised because I was almost sure Rails had this validator even though it felt strange a bit because I know that #nil? is first-class "no! no!". I was sure I had no gem for it, and that was correct. 

I found a file app/validators/not_nil_validator.rb

```ruby
class NotNilValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		record.errors.add(attribute, I18n.t!('activerecord.errors.messages.blank')) if value.nil?
	end
end
```

I put it there in 2016 in the initial commit of the project. I didn’t even remember how to write a custom validator. It’s the only file there. And I use it only for the arrays in PostgreSQL.

**Comment by PeterMozesMerl** [comment] 2019-07-09 09:47
The master fixes the issue for integer[]
One of my project has a character varying[] field too. The master branch didn’t fix that one. The message is the same:

'After setting :filters to ‹""› -- which was read back as ‹[]› -- the ...'

**Comment by mcmire** [comment] 2019-07-09 15:39
@PeterMozesMerl Ah, gotcha. Okay, let me take another look at it and get back to you.

**Comment by mcmire** [comment] 2019-07-10 05:56
@PeterMozesMerl Okay, I did some local tests with an array column that was a varchar, and I was able to reproduce your failure, but only if I did _not_ have a presence validation on the attribute. So, do you have a presence validation on your `filters` attribute?

**Comment by PeterMozesMerl** [comment] 2019-07-10 09:37
Yes. I do. I double-checked it with two models. The db-related comments were generated by the 'annotate' gem.

```ruby
#  entity_ids    :integer          default([]), not null, is an Array
	validates :entity_ids, not_nil: true
# ...

#  filters                      :string           default([]), not null, is an Array
	validates :filters, not_nil: true
```

4.0.1:

```
$ bundle update && rspec spec/models/email_spec.rb spec/models/message_spec.rb
Finished in 8.03 seconds (files took 1.63 seconds to load)
35 examples, 0 failures
```

Gem without version:
```
35 examples, 2 failures

Failed examples:

rspec ./spec/models/email_spec.rb[1:1:1] # Email Presence validation should validate that :entity_ids cannot be empty/falsy
rspec ./spec/models/message_spec.rb[1:1:3] # Message Presence validation should validate that :filters cannot be empty/falsy
```

Using "gem 'shoulda-matchers', git: 'https://github.com/thoughtbot/shoulda-matchers.git'":

```
Finished in 8.33 seconds (files took 2.03 seconds to load)
35 examples, 1 failure

Failed examples:

rspec ./spec/models/message_spec.rb[1:1:3] # Message Presence validation should validate that :filters cannot be empty/falsy

```

I copy-pasted everything to eliminate any mistake.

Maybe I will create a test project for you soon.

**Comment by PeterMozesMerl** [comment] 2019-07-10 10:29
Rails 5.2.3, PostgreSQL

I removed the .ruby-version file and the Ruby version from the Gemfile as they break RVM on Mac at the moment.

The Gemfile has three versions of shoulda-matchers. (Two commented out).

bundle
rails db:create
rails db:migrate
rspec

https://drive.google.com/open?id=1eBF-ekKXxcpMyQgRhvShLu2usTFG-rEs

**Comment by mcmire** [comment] 2019-07-11 04:41
Ah... I gotcha. Okay, I see what's going on now.

So, I have a suggestion, and you may not like it, but it's this: I would suggest _not_ using `validate_presence_of` in this case. The reason I say this is because you're not actually using a presence validation on your `favorite_numbers` (or `filters`) attribute. Here's the thing: even if I prevented the presence matcher from setting your attribute to an empty string (which I can certainly do), if the presence matcher were to do a complete job of testing that the presence validation is on your attribute — which is what it was originally designed to do — the matcher should also be making sure that your record is invalid when given an empty array, and not an empty string. (And in effect, that's what it's doing right now, because the empty string is getting converted into an empty array.) However, your `not_nil` validation is different from Rails' presence validation: it's not concerned with whether the attribute is present or empty, it only cares whether it is nil or not. So I don't think that using shoulda-matcher's presence matcher is appropriate here.

You mentioned using a shared context, and that would certainly work to test your `not_nil` validation. If you're feeling adventurous, you could also make your own matcher that does something like this:

* set the attribute to nil, assert that the record is invalid / has a validation error message
* set the attribute to an empty array, assert that the record is valid
* set the attribute to a non-empty array, assert that the record is valid

Such a matcher could look [something like this](https://gist.github.com/mcmire/c87dc92729be797ed81de24ab6aa4ecf).

Regardless of whatever method you choose, what do you think of this plan?

**Comment by PeterMozesMerl** [comment] 2019-07-11 08:40
"So, I have a suggestion, and you may not like it, but it's this: I would suggest not using validate_presence_of in this case."

It’s not true I don’t like it. I agree with you since I figured it out what I’ve been using a custom validator. 

When I opened the ticket, I believed that the not_nil was part of Rails. If it were true, I would consider it normal to have a related one-liner shoulda-matcher that other people could use too.

Now I see it as a corner case is useful only for one who focuses on the special features of PostgreSQL. It was lucky that it used to work. Even in the opening comment, I wrote that in general, I see the change that broke my examples an improvement of your code (from the Rails perspective since the presence validator isn’t for not nil but not blank).

I already wrote an RSpec extension for composite partial PostgreSQL indices. At least that code won’t be lonely, sitting there alone.

Thank you for your time, and for this gem, in general. It helped a lot over the years in many ways.

**Comment by mcmire** [comment] 2019-07-14 23:46
Of course! Cheers!

**Closed by mcmire** 2019-07-14 23:46 UTC
Labels: 🕷 Issue: Bug
