### ISSUE TITLE
validate_uniqueness_of(attribute).scoped_to(other_attribute) incorrectly fails with not null constraint

### ISSUE THREAD

**Issue by Dbz** [thoughtbot/shoulda-matchers#745] opened 2015-07-01 17:45 UTC
Hello, `validate_uniqueness_of(attribute).scoped_to(other_attribute)` will fail if there is a database not null constraint. Here is an example of my Rails migration:

```ruby
class CreateLabelJoins < ActiveRecord::Migration
  def change
    create_table :label_joins do |t|
      t.integer :node_id, null: false
      t.integer :label_id, null: false

      t.timestamps
    end
    add_index :label_joins, [:node_id, :label_id], unique: true
  end
end
```

And here is the model:

```ruby
class LabelJoin < ActiveRecord::Base
  validates_presence_of :node_id, :label_id
  validates_uniqueness_of :node_id, scope: :label_id

  belongs_to :node
  belongs_to :label
end
```

The test `it { should validate_uniqueness_of(:node_id).scoped_to(:label_id) }` fails with this error: 

    1) LabelJoin validations should require case sensitive unique value for node_id scoped to label_id
         Failure/Error: it { should validate_uniqueness_of(:node_id).scoped_to(:label_id) }
         ActiveRecord::StatementInvalid:
           PG::NotNullViolation: ERROR:  null value in column "label_id" violates not-null constraint
           DETAIL:  Failing row contains (1, 0, null, 2015-07-01 17:37:46.150481, 2015-07-01 17:37:46.150481).
           : INSERT INTO "label_joins" ("created_at", "node_id", "updated_at") VALUES ($1, $2, $3) RETURNING "id"
         # ./spec/models/label_join_spec.rb:7:in `block (3 levels) in <top (required)>'

I believe the issue would be resolved if I remove the composite index line `add_index :label_joins, [:node_id, :label_id], unique: true`, but I wish to have the constraint in both the model and database layers.

**Comment by bvicenzo** [comment] 2015-07-16 21:01
Hello Guys, I'm having the same problem. And I beleive i've found the cause.
[Here](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L325), when there is no database register, it tries to create the first one. However it tries to do this with [validate = false](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb#L356) and does not care in to fill other fields which would be important to database consistence.
As a workaround, I've create the first record by myself before testing.
Like this:
```rb
it 'validates uniquess of node_id scoped to label_id' do
  LabelJoin.create(node_id: 1, label_id: 1) #and some attribute else which is needed to have the record saved on database
  should validate_uniqueness_of(:node_id).scoped_to(:label_id)
end
```

**Comment by Dbz** [comment] 2015-07-22 05:02
Thank you for posting. I actually found the same solution!

```Ruby
context "associations" do
    before { FactoryGirl.create(:user) }
    it { should have_many(:projects).dependent(:destroy) }
end
````

**Comment by mcmire** [comment] 2015-07-22 17:15
I'm going to close this. This is a [known issue](http://matchers.shoulda.io/docs/v2.8.0/Shoulda/Matchers/ActiveRecord.html#validate_uniqueness_of-instance_method) with `validate_uniqueness_of` and there isn't really a way around this other than to manually create the record.

**Closed by mcmire** 2015-07-22 17:15 UTC
Labels: Need to Investigate

**Comment by mikewiltbank** [comment] 2020-01-28 16:49
should validate_uniqueness_of(:node_id).scoped_to(:label_id).case_insensitive
