### ISSUE TITLE
`cast_type` use in rails_shim causes a problem with the serialize matcher - Rails 5

### ISSUE THREAD

**Issue by adammcfadden** [thoughtbot/shoulda-matchers#913] opened 2016-03-09 23:20 UTC
I have seen this issue in Rails 5, and shoulda-matchers 3.1.1 (along with pulling shoulda-matchers directly from master). 

```
IntakeRequest should serialize :payload class_name => JSON
     Failure/Error: should serialize(:payload).
     NoMethodError:
       undefined method `cast_type' for #<ActiveRecord::ConnectionAdapters::MySQL::Column:0x007f8dcc21d778>
```

This cast_type attribute has been removed from ActiveRecord::ConnectionAdapters::MySQL::Column per [this commit](https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749#diff-ece1d9e4cf3db41b2c394e2acfcc2330)

The cast_type attribute is called from within the [rails_shim](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/rails_shim.rb#L22)

I would be happy to help fix this, but could use some direction if anyone has suggestions on how best to address this.

**Note:** An issue was created by the cast_type change on the [oracle adapter](https://github.com/rsim/oracle-enhanced/issues/777) that may have useful information as they come to a resolution.

**Comment by adammcfadden** [comment] 2016-03-09 23:42
As another note, the serialized_attributes method has been [removed from Rails 5](https://github.com/rails/rails/pull/15704) which will cause issues within the [same method on the rails_shim](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/rails_shim.rb#L32)

**Comment by adammcfadden** [comment] 2016-03-11 21:03
I have a possible solution that is using similar logic as a [fix in rails_admin](https://github.com/iwz/rails_admin/commit/698f06a8f45c7c56038e9f6d442c9cbfb4065dfe)

/shoulda-matchers/lib/shoulda/matchers/rails_shim.rb:22
```
      def self.serialized_attributes_for(model)
        if defined?(::ActiveRecord::Type::Serialized)
          # Rails 5+
          model.columns.select do |column|
            model.type_for_attribute(column.name).is_a?(::ActiveRecord::Type::Serialized)
          end.inject({}) do |hash, column|
            hash[column.name.to_s] = model.type_for_attribute(column.name).coder.name.split("::").last.constantize
            hash
          end
        else
          model.serialized_attributes
        end
      end
```

I have tested this against the rails 5 app that I originally discovered the issue with, and the above solution seems to be working. I will work on adding more holistic testing in with a pull request, but that will take some time as it looks like shoulda-matchers is not yet testing against rails 5. 

If anyone has suggestions for refactoring (I would love to clean up ` hash[column.name.to_s] = model.type_for_attribute(column.name).coder.name.split("::").last.constantize
`), or info about testing against rails 5 please let me know.

**Comment by engineersmnky** [comment] 2016-04-05 18:10
@adammcfadden  `model.type_for_attribute(column.name).coder.name.split("::").last.constantize` seems like it could be `model.type_for_attribute(column.name).coder.demodulize.constantize` more or less the same thing under the covers but reads a little nicer.

**Comment by fubarius** [comment] 2016-05-03 00:32
Any update on this?

**Comment by adammcfadden** [comment] 2016-05-05 23:19
@fubarius I haven't put in any more work on this issue. I'm assuming that Rails 5 issues are waiting until rails 5 at least has a release candidate. @engineersmnky - nice, much cleaner!

**Comment by fubarius** [comment] 2016-05-06 02:00
@adammcfadden with your fix in place I hit another issue that's possibly in -context. I'll try to get the test suite passing against Rails 5 and start opening pull requests, though who knows when they'll get accepted thanks to the rather vague "changing of the guard" notice on the shoulda* projects.

**Comment by bsodmike** [comment] 2016-05-14 00:07
@adammcfadden I had to make a small change with respect to shoulda master, and it works a treat. Thanks!

```ruby
# spec/rails_helper.rb
module Shoulda
  module Matchers
    RailsShim.class_eval do
      def self.serialized_attributes_for(model)
        if defined?(::ActiveRecord::Type::Serialized)
          # Rails 5+
          model.columns.select do |column|
            model.type_for_attribute(column.name).is_a?(::ActiveRecord::Type::Serialized)
          end.inject({}) do |hash, column|
            hash[column.name.to_s] = model.type_for_attribute(column.name).coder
            hash
          end
        else
          model.serialized_attributes
        end
      end
    end
  end
end
```

**Comment by aried3r** [comment] 2016-07-08 12:07
Any news on this?

**Comment by anthonator** [comment] 2016-07-11 18:01
I'm seeing this as well

**Comment by leifg** [comment] 2016-07-18 13:16
Is there any particular problem with applying the mentioned monkey_patch of @bsodmike to RailsShim?

**Comment by Shomari** [comment] 2016-08-09 20:03
any update on this being patched?

**Comment by n-rodriguez** [comment] 2016-10-17 22:09
Hi! I confirm that @bsodmike's patch works :)

**Comment by bsodmike** [comment] 2016-10-18 00:06
Thanks @leifg @n-rodriguez - I've just posted a PR for this patch.

**Comment by laertispappas** [comment] 2017-07-07 11:21
When will this be fixed and released?

**Comment by mcmire** [comment] 2017-07-25 17:38
I merged @bsodmike's fix into the `rails-5` branch in 28a43a3b6081deb65dc1a25a5cd6f9608728c467, so I'm going to close this to clean things up. We'll have a new pre-release out soon so people can use that instead of having to use a branch in their Gemfiles.

**Closed by mcmire** 2017-07-25 17:38 UTC
Labels: Rails 5

**Comment by jeremywadsack** [comment] 2018-01-18 04:22
@mcmire Any progress on a pre-release? We're still using the branch.

**Comment by mcmire** [comment] 2018-01-20 19:58
@jeremywadsack Sigh. Somewhat. I've been (very slowly) working on improving some of the messages so I can debug some of the current issues better. But at this point it's completely backing things up. I'll take a look at what's left over and see if I can just finish up the remaining Rails 5 issues and put something out (even it's just an alpha) soon.

**Comment by javierojeda94** [comment] 2018-01-26 18:03
For the people who are using the master branch, how can we fix this? Is there a workaround while we wait for the fix?

**Comment by mcmire** [comment] 2018-01-26 20:11
@javierojeda94 It should be fixed already, in master.  Are you still experiencing issues?

**Comment by javierojeda94** [comment] 2018-01-26 21:13
Yes. I'm using rspec to test a serialization field on my model but I'm facint some errors on those tests:

My model `make.rb`
```ruby
class Make < ApplicationRecord
  serialize :vehicle_types, Array
end
```

When I run the example `it { is_expected.to serialize(:vehicle_types).as(Array) }`

I got this error:
```
NoMethodError:
       undefined method `cast_type' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x0000564663634340>
```

In my `Gemfile.lock` I have `shoulda-matchers (3.1.2)`

**Comment by mcmire** [comment] 2018-01-27 01:14
@javierojeda94 Hmm, you shouldn't be seeing that. You sure you're pointed to master? You may want to run `bundle update` to ensure that you're pointed to the latest commit.

**Comment by dillionverma** [comment] 2018-03-23 02:02
Any update on this? I recently experienced this issue.

**Comment by blackst0ne** [comment] 2018-04-03 01:54
@mcmire 

Any news?

**Comment by steobrien** [comment] 2018-04-16 23:58
I can confirm this works perfectly on master.

A quick note to others, ensure you're following the master branch of this repository:
```ruby
# Gemfile
gem "shoulda-matchers", git: "https://github.com/thoughtbot/shoulda-matchers"
```

@mcmire thanks again for the patch! It would be great to get this into an official release soon.

**Comment by aried3r** [comment] 2018-04-18 14:55
Even a .beta or .rc1 version would be very much appreciated. :)

**Comment by yagudaev** [comment] 2018-08-23 20:03
Yep it would be nice to get a new version of shoulda-matchers out, last update was over a year ago.

https://rubygems.org/gems/shoulda-matchers/versions/3.1.2

**Comment by jeremywadsack** [comment] 2018-12-12 20:17
For the record, it looks like 4.0.0.rc1 was released in Oct with Rails 5 support.
