### ISSUE TITLE
has_many test with a condition, where condition is a scope

### ISSUE THREAD

**Issue by abitdodgy** [thoughtbot/shoulda-matchers#716] opened 2015-05-12 17:13 UTC
Is there a way to test a has_many through relation with a condition, where the condition is a lambda pointing to a scope in another class?

Let's assume we have a Membership model that joins a many to many relation between a User and a Workspace model. The membership has a role column.

```
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :workspace

  scope :admin, -> { where(role: :admin) }
```

We want to get users with a 'admin' role:

```ruby
class Workspace < ActiveRecord::Base
  has_many :memberships
  has_many :members, through: :memberships, source: :user
  has_many :admins, -> { Membership.admin }, through: :memberships, source: :user
end
```

Is there a way to test this? I know I can do it manually, but I'm curious to see if this is possible. I tried this:

```ruby
should have_many(:admins).through(:memberships).conditions(memberships: { role: :admin })
```

Which fails:

```
 1) Failure:
WorkspaceTest#test_: Workspace should have many admins through memberships.  [/Users/Mohamad/.rvm/gems/ruby-2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:344]:
Expected Workspace to have a has_many association called admins (admins should have the following conditions: {:memberships=>{:role=>:admin}})
```

**Comment by mcmire** [comment] 2015-05-12 20:24
There isn't yet, unfortunately. The issue is that conditions can always be specified multiple ways, so we have to attempt to normalize them when we get them in. Normalization is pretty naive. It passes the conditions to the model that the association will return -- so `User.where(memberships: { role: :admin })` in this case -- then asks ActiveRecord what its internal representation of those conditions are. I don't think that's quite correct -- I'd have to find out how ActiveRecord takes your lambda and mixes it into the relation for the association and mimic that, I think.

**Comment by abitdodgy** [comment] 2015-05-12 21:18
Yeah, you would have to account for the join, I believe. In this case the equivalent would likely be `User.joins(:memberships).where(memberships: { role: :admin })`. But I don't know enough about this to say with certainty. I'm not sure if I would label this as a bug, though. It sounds more like a feature.

**Comment by mcmire** [comment] 2015-05-13 01:49
Good point.

**Comment by abitdodgy** [comment] 2015-06-03 13:10
@mcmire I'd like to close this issue. I think I made a mistake. The column I was using as a condition is an enum column. Using my example above, this works: (2 translates to :admin by Rails).

```ruby
should have_many(:admins).through(:memberships).conditions(role: 2)
```

The failing example had this:

```ruby
should have_many(:admins).through(:memberships).conditions(memberships: { role: :admin })
```

So this looks like a none issue. Thoughts, or can we close this?

**Comment by mcmire** [comment] 2015-06-03 15:18
Oh cool, that's good news, I'm glad to see that works. Okay, I'll close this.

**Closed by mcmire** 2015-06-03 15:18 UTC
Labels: Feature Request

**Comment by TorvaldsDB** [comment] 2018-09-07 02:56
My model `follow.rb` looks like this: 
```ruby
class Follow < ApplicationRecord
  belongs_to :staff

  scope :actual, -> do
    sql = <<-sql
      select m.id, m.user_id, m.staff_id, t.min_followed_at from (
        select user_id, min(created_at) as min_followed_at
        from follows group by user_id
      ) t join follows m on m.user_id = t.user_id and t.min_followed_at = m.created_at;
    sql

    ids = find_by_sql(sql).pluck(:id)
    where(id: ids)
  end
end
```
and my `staff.rb` looks like this:
```ruby
class Staff < ApplicationRecord
  has_many :direct_follows, -> { actual }, class_name: "Follow"
end
```
how should I write the test-file to test the`-> {actual}`
```ruby
require 'rails_helper'

RSpec.describe Staff, type: :model do
  #it { is_expected.to have_many(:direct_follows).class_name("Follow") }
end
```
Anyway, Thank you very much.

**Comment by mcmire** [comment] 2018-09-07 04:19
@TorvaldsDB Since you have a custom query, I would honestly test it manually -- call `staff.direct_follows` and then assert the return value.

**Comment by TorvaldsDB** [comment] 2018-09-10 07:44
@mcmire I am sorry to reply to you now.`staff.direct_follows` will return a relation of `Follow`. Ignore it.  May I return to the problem itself. I wanna to test the `-> { actual }`. This represents a similar problem of this kind about a block which is not `where()` or `order`. I had already skipped this test in my project. so I wanna the solution about it.

**Comment by TorvaldsDB** [comment] 2018-09-13 09:14
@mcmire oha, I seeeee. Thank you a lot.

**Comment by zernie** [comment] 2022-01-28 12:59
@mcmire hey, but can we at least add some method that assures some scope was called? e.g.

`it { is_expected.to have_many(:fresh_posts).through(:comments).with_scope(:fresh) }`
