### ISSUE TITLE
Validating uniqueness on an association column seems to fail with a presence validation on the association

### ISSUE THREAD

**Issue by brandonweiss** [thoughtbot/shoulda-matchers#880] opened 2016-01-12 15:39 UTC
```ruby
belongs_to :customer

validates :customer, presence: true
validates :customer_id, uniqueness: true
```

```ruby
it { should validate_uniqueness_of :customer_id }
```

```
SomeClass did not properly validate that :customer_id
is case-sensitively unique.
  The record you provided could not be created, as it failed with the
  following validation errors:
     
* customer: ["can't be blank"]
```

**Comment by j15e** [comment] 2016-01-12 16:45
I also found this issue with `3.1.0` (I updated to get the #849 fix).

I guess I could use a model instance with values rather than the class to work around issue this, but the specs won't be as isolated and as fast as they are.

**Comment by mcmire** [comment] 2016-01-12 17:06
Ah, I was a little overzealous in providing some more checks that I thought would be useful. You're right that this won't work. I'll remove that check.

**Comment by brandonweiss** [comment] 2016-01-12 19:27
Thanks!

**Comment by jasnow** [comment] 2016-01-12 20:42
Wow - just finished writing the issue up:

Appears that the shoulda-matcher(3.1.0)'s validate_uniqueness_of  can not support "can't be blank"

Steps to reproduce:

 1. Clone this repo locally: https://github.com/24pullrequests/24pullrequests

 2. Remove the "skip"s in these two files: spec/models/project_label_spec.rb, spec/models/project_spec.rb

 3. Ran "rake" and you get output similar to this gist: https://gist.github.com/jasnow/0d0a88b68c8db4b68107
    
 4. It worked in 3.0.1.

**Comment by mcmire** [comment] 2016-01-13 00:29
Sorry... just a oversight on my part. Amazing how one little change can break everything.

I'll try to get another release out soon with a fix for this.

**Comment by hugocorbucci** [comment] 2016-01-13 18:46
:+1: Hitting this issue too.
Thanks @mcmire for looking into it and fixing it this quickly!

**Comment by BitPuncher** [comment] 2016-01-13 22:11
I presume this is the same problem but just in case its not, I have a bunch of uniqueness validation expectations, not just on association columns, that fail due to every other validation failing on the object.

As an example:
```
class GroupAction < RolloutAction
  strip_attributes
  attr_accessible :action, :rollout_group

  validates :rollout_group, presence: true, uniqueness: {scope: :feature, message: "%{value} has already been assigned once for this feature."}

  # as well as these inherited validations
  ALLOWED_TYPES = %w(GroupAction UserAction PercentageAction)
  ALLOWED_ACTIONS = %w(activate deactivate)

  validates :type, :action, :feature, presence: true
  validates :type, inclusion: { in: ALLOWED_TYPES }
  validates :action, inclusion: { in: ALLOWED_ACTIONS }
end
```

With the following specs:
```
describe GroupAction do
  let(:group_action) { build :group_action }

  describe '#valid' do
    it { is_expected.to validate_uniqueness_of(:rollout_group).scoped_to(:feature).with_message(/has already been assigned once/) }
  end
end
```
Gives the following failure:
```
  1) GroupAction#valid should validate that :rollout_group is case-sensitively unique within the scope of :feature, producing a custom validation error on failure
     Failure/Error: it { is_expected.to validate_uniqueness_of(:rollout_group).scoped_to(:feature).with_message(/has already been assigned once/) }
       GroupAction did not properly validate that :rollout_group is
       case-sensitively unique within the scope of :feature, producing a custom
       validation error on failure.
         The record you provided could not be created, as it failed with the
         following validation errors:
       
         * action: ["can't be blank", "is not included in the list"]
         * feature: ["can't be blank"]
         * rollout_group: ["can't be blank"]
     # ./spec/models/group_action_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 0.10336 seconds (files took 6.16 seconds to load)
1 example, 1 failure
```

**Comment by mcmire** [comment] 2016-01-13 22:57
Yeah, it's likely the same problem. Sorry about that.

**Comment by mcmire** [comment] 2016-01-16 16:58
@BitPuncher Actually, I don't know if that test would have passed even on 3.0.1. The matcher requires a record to be in the database, and there's not one, it'll take the record you provide and try to save it. So that probably would have failed validation. Do you think you can confirm that on 3.0.1?

**Comment by BitPuncher** [comment] 2016-01-19 21:49
Sorry I had to fix something else in my factory that was causing a break to make sure it was unrelated. It passes when I revert to 3.0.1 and in 3.1.0 it continues to break. I changed the factory to be a `{ create :group_action }` and it fails the same way while passing in the former version.

**Comment by jpkeane** [comment] 2016-01-19 22:55
Thanks for the quick response! Falling back to 3.0.1 until 3.1.1 released. 

Just to confirm, for me, all validate_uniqueness_of fails for me whilst I have a Postgres DB constraint for NOT NULL on the value being checked.

**Comment by jpkeane** [comment] 2016-01-19 22:58
Can see how it slipped the net, cant recreate without the NOT NULL constraint on the DB. Anyone with better TDD skills than me now a way to spec that out?

**Comment by mcmire** [comment] 2016-01-19 23:45
A fix for this is now in master: 45de8698487d57f559c5bf35818d1c1ee82b0e77

**Comment by jpkeane** [comment] 2016-01-20 01:08
Tested fix on the above use case, work with patch 45de8698487d57f559c5bf35818d1c1ee82b0e77

**Comment by brandonweiss** [comment] 2016-01-22 00:07
Thanks so much! Release plz :grin:

**Comment by vinhnglx** [comment] 2016-01-24 17:35
Thanks :) I'm waiting for this release :smiley:

**Comment by acandael** [comment] 2016-01-26 09:07
Having this issue too. Waiting for the next release

**Comment by mcmire** [comment] 2016-01-28 07:23
3.1.1 is now available!

**Closed by mcmire** 2016-01-28 07:23 UTC

**Comment by birhanuh** [comment] 2016-05-19 21:06
I have updated to 3.1.1. And still have the issue. Is there coming a new release with this issue fixed?

**Comment by jasnow** [comment] 2016-05-20 11:00
@birhanuh - Is your repo public? If so, I will try to help understand the issue.

**Comment by birhanuh** [comment] 2016-05-20 11:05
Hi @jasnow 
Yes, it is public. I just merged my branch to master. 
Here: [https://github.com/toolsio-com/toolsio](url)

Thanks for the help in advance.

**Comment by mcmire** [comment] 2016-06-14 01:40
@birhanuh I can't seem to access your repo.

Could you create a new issue and post a snippet of the code that doesn't work for you and the errors you're getting? That would help me look into it further. Thanks!

**Comment by grammakov** [comment] 2016-10-21 15:18
Facing the same problem over here.

**Comment by mcmire** [comment] 2016-10-21 19:53
@grammakov Since this one is closed, can you post a new issue with the shoulda-matchers version you're using and the Rails version you're using?

**Comment by grammakov** [comment] 2016-10-22 09:11
@mcmire absolutely. Done. Thanks!
