### ISSUE TITLE
allow_values not properly checking each value?

### ISSUE THREAD

**Issue by backus** [thoughtbot/shoulda-matchers#845] opened 2015-11-18 03:41 UTC
The `allow_values` matcher seems to not fail if it is given multiple values when the first is valid.  I believe this reproduces on master:

```ruby
require 'date'
require 'active_model'
require 'shoulda/matchers'

class Example
  include ActiveModel::Model

  validates :foo, inclusion: [1]

  attr_accessor :foo
end

RSpec.describe Example do
  include Shoulda::Matchers::ActiveModel

  subject { described_class.new }

  it { should allow_values(1).for(:foo)    } # this should pass and does
  it { should allow_values(2).for(:foo)    } # this should fail and does
  it { should allow_values(2, 1).for(:foo) } # this should fail and does
  it { should allow_values(1, 2).for(:foo) } # this should fail and doesn't
end
```

produces

```txt
Example
  should allow foo to be set to 1
  should allow foo to be set to 2 (FAILED - 1)
  should allow foo to be set to any of [2, 1] (FAILED - 2)
  should allow foo to be set to any of [1, 2]

Failures:

  1) Example should allow foo to be set to 2
     Failure/Error: it { should allow_values(2).for(:foo)    } # this should fail and does

       Did not expect errors when foo is set to 2,
       got errors:
       * "is not included in the list" (attribute: foo, value: 2)
     # ./example_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Example should allow foo to be set to any of [2, 1]
     Failure/Error: it { should allow_values(2, 1).for(:foo) } # this should fail and does

       Did not expect errors when foo is set to 2,
       got errors:
       * "is not included in the list" (attribute: foo, value: 2)
     # ./example_spec.rb:12:in `block (2 levels) in <top (required)>'

Finished in 0.40018 seconds (files took 1.86 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./example_spec.rb:11 # Example should allow foo to be set to 2
rspec ./example_spec.rb:12 # Example should allow foo to be set to any of [2, 1]
```

gist you can clone and run: https://gist.github.com/backus/254d29794f1efad11c13

**Comment by backus** [comment] 2015-11-18 19:23
Bisecting this behavior points to https://github.com/thoughtbot/shoulda-matchers/commit/19c38a642a2ae1316ef12540a0185cd026901e74. Would be interesting to get your input @mcmire.  I'm still not 100% clear on whether I am encountering a bug or if this is expected behavior

**Comment by mcmire** [comment] 2015-11-18 22:18
@backus This is definitely a mystery for me too.

Taking a look at the validation, shouldn't it be this?

``` ruby
class Example
  include ActiveModel::Model

  # previously was simply `inclusion: [1]`
  validates :foo, inclusion: { in: [1] }

  attr_accessor :foo
end
```

Alternatively, what happens if you use this instead?

``` ruby
validate_inclusion_of :foo, in: [1]
```

**Comment by backus** [comment] 2015-11-18 22:19
Taking a look now!

**Comment by backus** [comment] 2015-11-18 22:23
@mcmire Each case seems to yield the same output.  I can create a gist if you would like

**Comment by mcmire** [comment] 2015-11-18 22:41
It's fine. I'm traveling right now, but I'll take a closer look at this later.

**Comment by lenart** [comment] 2015-12-02 14:45
Got to the same problem using different validation. Here's my test code:

### Model

```ruby
class Post
  include ActiveModel::Model

  attr_accessor :color

  validates :color, format: { with: /\A#[a-f0-9]{6}\z/ }
end
```

### Spec

```ruby
require "rails_helper"

RSpec.describe Post, type: :model do
  it { is_expected.to allow_values('#ffffff', '#FFFFFF').for(:color) } # passes but shouldn't
  it { is_expected.to allow_values('#FFFFFF', '#ffffff').for(:color) } # fails as expected
end
```

For debugging purposes here are some gem versions:

```
- rspec-rails (3.4.0)
- rspec-core (3.4.1)
- rspec-expectations (3.4.0)
- rspec-mocks (3.4.0)
- rspec-support (3.4.1)
- shoulda-matchers (3.0.1)
- spring (1.3.6)
- spring-commands-rspec (1.0.4)
```

**Comment by mcmire** [comment] 2015-12-02 18:02
I don't know this for sure, but I believe what may be happening is that the results of running the validation for the first value you're passing are [getting cached](https://github.com/thoughtbot/shoulda-matchers/blob/master/lib/shoulda/matchers/active_model/validator.rb#L35). Unfortunately, the `allow_value` matcher is highly stateful and objects are being reused while the matcher is iterating over all of the values. I would not be surprised if this has something to do with it.

We have [somewhat of a test](https://github.com/thoughtbot/shoulda-matchers/blob/master/spec/unit/shoulda/matchers/active_model/allow_value_matcher_spec.rb#L201) that mimics what you have in your test, but I don't think it's doing the right thing.

I am working on a change right now that will end up changing the `allow_value` matcher so that it is not as stateful. I think it may end up fixing this issue. I'll report back when I have that merged.

**Comment by ojab** [comment] 2015-12-25 13:34
Tried to use shoulda-matchers for the first time, hit it :(.

**Comment by mcmire** [comment] 2015-12-25 16:12
@ojab Yes, it's likely that that commit ended up fixing this issue. I never confirmed that though. Since a bug is present in the current version, we probably have a test that's missing. I would be grateful if someone could go in and write a failing test for this -- otherwise, I'll go in after I'm done with the PR (#866) I'm currently working on.

**Comment by ojab** [comment] 2015-12-26 16:54
Actually the test [was added](https://github.com/thoughtbot/shoulda-matchers/commit/583be384c359f4cc37968c1905382cb4807df11e#diff-0340393bbed1d14d1761fded1ab3cd0cR95) in 583be38.

**Comment by mcmire** [comment] 2016-01-10 08:30
I've [added some tests](https://github.com/thoughtbot/shoulda-matchers/commit/2aee2f4168d3e639d9d88e691e2944c0ad0e50bb) to prevent this from happening again in the future. They all pass, so I'm closing this issue now.

**Closed by mcmire** 2016-01-10 08:30 UTC
Labels: Need to Investigate

**Comment by backus** [comment] 2016-01-10 11:59
Thanks!
